Add missing fields to GROUP BY clause
PostgreSQL requires all non-aggregated fields to be in the GROUP BY
clause, if at least one aggregation function (such as COUNT) is used.

The corresponding error is:
  ERROR: column "bp_user.user_id" must appear in the GROUP BY clause
  or be used in an aggregate function